# Generated by Django 5.2 on 2025-04-21 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Modul sarlavhasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Modul tavsifi')),
                ('order', models.PositiveIntegerField(default=0, help_text="Modullarni ko'rsatish tartibi.", verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=255, verbose_name='Kurs sarlavhasi')),
                ('content', models.TextField(help_text='Kursning asosiy matnli mazmuni.', verbose_name='Kontent (mavzu)')),
                ('video_url', models.URLField(blank=True, help_text="Agar mavjud bo'lsa, YouTube video havolasi.", null=True, verbose_name='Video havolasi (YouTube)')),
                ('order', models.PositiveIntegerField(default=0, help_text="Modul ichidagi kurslarni ko'rsatish tartibi.", verbose_name='Tartib raqami')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.module', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('text', models.CharField(max_length=255, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, help_text="Agar bu javob to'g'ri bo'lsa belgilang.", verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['question', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=255, verbose_name='Test sarlavhasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Test tavsifi')),
                ('passing_score_percent', models.PositiveIntegerField(default=70, help_text="Testdan muvaffaqiyatli o'tish uchun talab qilinadigan minimal foiz.", verbose_name="O'tish bali (foizda)")),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.module', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('score', models.PositiveIntegerField(default=0, verbose_name="To'plangan ball (foizda)")),
                ('passed', models.BooleanField(default=False, verbose_name="O'tdi")),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Urinish vaqti')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='core.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Test Natijasi',
                'verbose_name_plural': 'Foydalanuvchilar Test Natijalari',
                'ordering': ['user', 'test', '-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Sertifikat ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates_issued', to='core.module', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['user', '-issued_at'],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Tugatilgan vaqti')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.course', verbose_name='Kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Kurs Progressi',
                'verbose_name_plural': 'Foydalanuvchilar Kurs Progresslari',
                'ordering': ['user', '-completed_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
