# Generated by Django 5.2 on 2025-04-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['module__order', 'order', 'title'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['module__order', 'module__title'], 'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterField(
            model_name='test',
            name='passing_score_percent',
            field=models.PositiveIntegerField(default=70, help_text="Testdan muvaffaqiyatli o'tish uchun talab qilinadigan minimal foiz (0-100).", verbose_name="O'tish bali (foizda)"),
        ),
    ]
