# Generated by Django 5.2.16 on 2026-09-12 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_options_alter_test_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='infographics/%Y/%m/', verbose_name='Infografika rasmi')),
                ('caption', models.CharField(blank=True, help_text="Karusel ostida ko'rinadigan qisqa matn.", max_length=300, verbose_name='Qisqa axborot')),
                ('link', models.URLField(blank=True, help_text='Bosilganda ochiladigan ixtiyoriy havola.', verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="Bosh sahifada ko'rsatilsinmi?", verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Infografika',
                'verbose_name_plural': 'Infografikalar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=200, verbose_name='Hujjat sarlavhasi')),
                ('document_type', models.CharField(choices=[('program', 'Kurs dasturi'), ('plan', 'Ish reja'), ('legal', 'Huquqiy asoslar'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Hujjat turi')),
                ('file', models.FileField(help_text='PDF yoki Word (.doc, .docx) fayllarni yuklang.', upload_to='site_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx'), message='Faqat PDF, DOC yoki DOCX fayllarni yuklash mumkin.')], verbose_name='Fayl (PDF/Word)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="Bosh sahifada ko'rsatilsinmi?", verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Sayt hujjati',
                'verbose_name_plural': 'Sayt hujjatlari (dastur, ish reja)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='coursesyllabus',
            options={'ordering': ['course', 'created_at'], 'verbose_name': "Ma'ruza materiali", 'verbose_name_plural': "Ma'ruza materiallari"},
        ),
        migrations.AlterField(
            model_name='coursesyllabus',
            name='file',
            field=models.FileField(help_text='PDF yoki Word (.doc, .docx) fayllarni yuklang.', upload_to='course_syllabi/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx'), message='Faqat PDF, DOC yoki DOCX fayllarni yuklash mumkin.')], verbose_name="Ma'ruza / material fayli"),
        ),
        migrations.AlterField(
            model_name='test',
            name='passing_score_percent',
            field=models.PositiveIntegerField(default=70, help_text="Testdan muvaffaqiyatli o'tish uchun talab qilinadigan minimal foiz (0-100).", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="O'tish bali (foizda)"),
        ),
    ]
